apiVersion: apps/v1
kind: Deployment

metadata:
  name: search-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: search-service

  template:
    metadata:
      labels:
        app: search-service

    spec:
      containers:
      - name: payment-service
        image: 093435167670.dkr.ecr.ap-southeast-1.amazonaws.com/search-service:IMAGE_TAG
        ports:
        - containerPort: 5000